# Generated by Django 5.2.7 on 2025-12-01 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.PositiveIntegerField(help_text='Max people per slot')),
                ('image_url', models.URLField(blank=True, help_text='URL to an image of the facility')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('time_slot', models.CharField(choices=[('09:00-11:00', 'Morning (9 AM - 11 AM)'), ('12:00-14:00', 'Afternoon (12 PM - 2 PM)'), ('15:00-17:00', 'Evening (3 PM - 5 PM)'), ('18:00-20:00', 'Night (6 PM - 8 PM)')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_bookings', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='facilities.facility')),
            ],
            options={
                'unique_together': {('facility', 'booking_date', 'time_slot')},
            },
        ),
    ]
