# Generated by Django 5.2.7 on 2026-01-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_facility_google_maps_url_facility_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_checked_in',
            field=models.BooleanField(default=False),
        ),
    ]
