# Generated by Django 5.2.7 on 2025-12-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='google_maps_url',
            field=models.URLField(blank=True),
        ),
    ]
