# Generated by Django 5.2.7 on 2026-01-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_parkinglot_google_maps_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingbooking',
            name='is_checked_in',
            field=models.BooleanField(default=False),
        ),
    ]
